#!/usr/bin/env python3

import re

zip_h_err = []
zipint_h_err = []

zip_err_str = ""

with open("zip.h", "r") as f:
    zip_h_str = f.read()
    zip_h_err = re.findall(
        "#define ZIP_ER_([A-Z0-9_]+) ([0-9]+)[ \t]+/([-*0-9a-zA-Z, ']*)/",
        zip_h_str
    )

with open("zipint.h", "r") as f:
    zipint_h_str = f.read()
    zipint_h_err = re.findall(
        "#define ZIP_ER_DETAIL_([A-Z0-9_]+) ([0-9]+)[ \t]+/([-*0-9a-zA-Z, ']*)/",
        zipint_h_str
    )

zip_err_str += '''
/* This file was generated by a python script. */
/* Do not modify. */

#include "zipint.h"

#define L ZIP_ET_LIBZIP
#define N ZIP_ET_NONE
#define S ZIP_ET_SYS
#define Z ZIP_ET_ZLIB

#define E ZIP_DETAIL_ET_ENTRY
#define G ZIP_DETAIL_ET_GLOBAL

const struct _zip_err_info _zip_err_str[] = {
'''

for err in zip_h_err:
    match = re.search("([L|N|S|Z]+) ([-0-9a-zA-Z,, ']*)", err[2])
    err_type = match[1]
    err_desc = f"\"{match[2][:-1]}\""
    zip_err_str += "    {%s, %s},\n" % (err_type, err_desc)

zip_err_str += '''};

const int _zip_err_str_count = sizeof(_zip_err_str)/sizeof(_zip_err_str[0]);

const struct _zip_err_info _zip_err_details[] = {
'''

for err in zipint_h_err:
    match = re.search("([E|G]+) ([-0-9a-zA-Z, ']*)", err[2]);
    err_type = match[1]
    err_desc = f"\"{match[2][:-1]}\""
    zip_err_str += "    {%s, %s},\n" % (err_type, err_desc)

zip_err_str += '''};

const int _zip_err_details_count = sizeof(_zip_err_details)/sizeof(_zip_err_details[0]);
'''

with open('zip_err_str.c', 'w') as f:
    f.write(zip_err_str)
